<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
class AccperkiraanSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('accperkiraan')->insert([
            [    
                'induk_acc' => 'NULL',
                'kode_acc' => '1-0000',
                'nama_acc' => 'AKTIVA',
                'kelompok' => 1,
                'tipe' => 'HD',
                'kas' => 0,
                'bank' => 0,
                'posisi' => 'D',

            ],
            [    
                'induk_acc' => '1-0000',
                'kode_acc' => '1-1000',
                'nama_acc' => 'AKTIVA LANCAR',
                'kelompok' => 1,
                'tipe' => 'HD',
                'kas' => 0,
                'bank' => 0,
                'posisi' => 'D',

            ],
            [    
                'induk_acc' => '1-1000',
                'kode_acc' => '1-1100',
                'nama_acc' => 'KAS & BANK',
                'kelompok' => 1,
                'tipe' => 'HD',
                'kas' => 0,
                'bank' => 0,
                'posisi' => 'D',
            ],
            [    
                'induk_acc' => '1-1100',
                'kode_acc' => '1-1110',
                'nama_acc' => 'KAS KECIL',
                'kelompok' => 1,
                'tipe' => 'DT',
                'kas' => 1,
                'bank' => 0,
                'posisi' => 'D',
            ],
            [    
                'induk_acc' => '1-1100',
                'kode_acc' => '1-1111',
                'nama_acc' => 'KAS BESAR',
                'kelompok' => 1,
                'tipe' => 'DT',
                'kas' => 1,
                'bank' => 0,
                'posisi' => 'D',
            ],
            [    
                'induk_acc' => '1-1100',
                'kode_acc' => '1-1120',
                'nama_acc' => 'BANK BCA',
                'kelompok' => 1,
                'tipe' => 'DT',
                'kas' => 0,
                'bank' => 1,
                'posisi' => 'D',
            ],
            [    
                'induk_acc' => '1-1100',
                'kode_acc' => '1-1121',
                'nama_acc' => 'BANK BRI',
                'kelompok' => 1,
                'tipe' => 'DT',
                'kas' => 0,
                'bank' => 1,
                'posisi' => 'D',
            ],
            [    
                'induk_acc' => '1-1000',
                'kode_acc' => '1-1200',
                'nama_acc' => 'PIUTANG',
                'kelompok' => 1,
                'tipe' => 'HD',
                'kas' => 0,
                'bank' => 0,
                'posisi' => 'D',
            ],
            [    
                'induk_acc' => '1-1200',
                'kode_acc' => '1-1210',
                'nama_acc' => 'PIUTANG DAGANG',
                'kelompok' => 1,
                'tipe' => 'DT',
                'kas' => 0,
                'bank' => 0,
                'posisi' => 'D',
            ],
            [    
                'induk_acc' => '1-1200',
                'kode_acc' => '1-1220',
                'nama_acc' => 'PIUTANG KARTU KREDIT',
                'kelompok' => 1,
                'tipe' => 'DT',
                'kas' => 0,
                'bank' => 0,
                'posisi' => 'D',
            ],
            [    
                'induk_acc' => '1-1200',
                'kode_acc' => '1-1230',
                'nama_acc' => 'PIUTANG KARTU DEBIT',
                'kelompok' => 1,
                'tipe' => 'DT',
                'kas' => 0,
                'bank' => 0,
                'posisi' => 'D',
            ],
            [    
                'induk_acc' => '1-2000',
                'kode_acc' => '1-1240',
                'nama_acc' => 'PIUTANG KARYAWAN',
                'kelompok' => 1,
                'tipe' => 'DT',
                'kas' => 0,
                'bank' => 0,
                'posisi' => 'D',
            ],
            [    
                'induk_acc' => '1-1200',
                'kode_acc' => '1-1250',
                'nama_acc' => 'PIUTANG PIHAK KETIGA (SUPLIER)',
                'kelompok' => 1,
                'tipe' => 'DT',
                'kas' => 0,
                'bank' => 0,
                'posisi' => 'D',
            ],
            [    
                'induk_acc' => '1-0000',
                'kode_acc' => '1-1300',
                'nama_acc' => 'PERSEDIAAN',
                'kelompok' => 1,
                'tipe' => 'HD',
                'kas' => 0,
                'bank' => 0,
                'posisi' => 'D',
            ],
            [    
                'induk_acc' => '1-1300',
                'kode_acc' => '1-1301',
                'nama_acc' => 'PERSEDIAAN SIAP JUAL',
                'kelompok' => 1,
                'tipe' => 'DT',
                'kas' => 0,
                'bank' => 0,
                'posisi' => 'D',
            ],
            [    
                'induk_acc' => '1-1300',
                'kode_acc' => '1-1302',
                'nama_acc' => 'PERSEDIAAN BAHAN PRODUKSI',
                'kelompok' => 1,
                'tipe' => 'DT',
                'kas' => 0,
                'bank' => 0,
                'posisi' => 'D',
            ],
            [    
                'induk_acc' => '1-1000',
                'kode_acc' => '1-1400',
                'nama_acc' => 'PAJAK PEMBELIAN',
                'kelompok' => 1,
                'tipe' => 'HD',
                'kas' => 0,
                'bank' => 0,
                'posisi' => 'D',
            ],
            [    
                'induk_acc' => '1-1400',
                'kode_acc' => '1-1410',
                'nama_acc' => 'PPN MASUKAN',
                'kelompok' => 1,
                'tipe' => 'DT',
                'kas' => 0,
                'bank' => 0,
                'posisi' => 'D',
            ],
            [    
                'induk_acc' => '1-1400',
                'kode_acc' => '1-1421',
                'nama_acc' => 'PAJAK BAYAR DIMUKA',
                'kelompok' => 1,
                'tipe' => 'DT',
                'kas' => 0,
                'bank' => 0,
                'posisi' => 'D',
            ],
            [    
                'induk_acc' => '1-0000',
                'kode_acc' => '1-2000',
                'nama_acc' => 'AKTIVIA TETAP',
                'kelompok' => 1,
                'tipe' => 'HD',
                'kas' => 0,
                'bank' => 0,
                'posisi' => 'D',
            ],
            [    
                'induk_acc' => '1-0000',
                'kode_acc' => '1-2001',
                'nama_acc' => 'NULL',
                'kelompok' => 1,
                'tipe' => 'DT',
                'kas' => 0,
                'bank' => 0,
                'posisi' => 'D',
            ],
            [    
                'induk_acc' => '1-2000',
                'kode_acc' => '1-2100',
                'nama_acc' => 'TANAH',
                'kelompok' => 1,
                'tipe' => 'DT',
                'kas' => 0,
                'bank' => 0,
                'posisi' => 'D',
            ],
            [    
                'induk_acc' => '1-2000',
                'kode_acc' => '1-2200',
                'nama_acc' => 'BANGUNAN',
                'kelompok' => 1,
                'tipe' => 'DT',
                'kas' => 0,
                'bank' => 0,
                'posisi' => 'D',
            ],
            [    
                'induk_acc' => '1-2000',
                'kode_acc' => '1-2201',
                'nama_acc' => 'AKUMULASI PENYUSUTAN BANGUNAN',
                'kelompok' => 1,
                'tipe' => 'DT',
                'kas' => 0,
                'bank' => 0,
                'posisi' => 'K',
            ],
            [    
                'induk_acc' => '1-2000',
                'kode_acc' => '1-2300',
                'nama_acc' => 'KENDARAAN',
                'kelompok' => 1,
                'tipe' => 'DT',
                'kas' => 0,
                'bank' => 0,
                'posisi' => 'D',
            ],
            [    
                'induk_acc' => '1-2000',
                'kode_acc' => '1-2301',
                'nama_acc' => 'AKUMULASI PENYUSUTAN KENDARAAN',
                'kelompok' => 1,
                'tipe' => 'DT',
                'kas' => 0,
                'bank' => 0,
                'posisi' => 'K',
            ],
            [    
                'induk_acc' => '1-2000',
                'kode_acc' => '1-2400',
                'nama_acc' => 'PERALATAN',
                'kelompok' => 1,
                'tipe' => 'DT',
                'kas' => 0,
                'bank' => 0,
                'posisi' => 'D',
            ],
            [    
                'induk_acc' => '1-2000',
                'kode_acc' => '1-2401',
                'nama_acc' => 'AKUMULASI PENYUSUTAN PERALATAN',
                'kelompok' => 1,
                'tipe' => 'DT',
                'kas' => 0,
                'bank' => 0,
                'posisi' => 'K',
            ],
            [    
                'induk_acc' => 'NULL',
                'kode_acc' => '2-0000',
                'nama_acc' => 'KEWAJIBAN',
                'kelompok' => 2,
                'tipe' => 'HD',
                'kas' => 0,
                'bank' => 0,
                'posisi' => 'K',
            ],
            [    
                'induk_acc' => '2-0000',
                'kode_acc' => '2-1000',
                'nama_acc' => 'KEWAJIBAN LANCAR',
                'kelompok' => 2,
                'tipe' => 'HD',
                'kas' => 0,
                'bank' => 0,
                'posisi' => 'K',
            ],
            [    
                'induk_acc' => '2-1000',
                'kode_acc' => '2-1100',
                'nama_acc' => 'HUTANG OPERASIONAL',
                'kelompok' => 2,
                'tipe' => 'HD',
                'kas' => 0,
                'bank' => 0,
                'posisi' => 'K',
            ],
            [    
                'induk_acc' => '2-1100',
                'kode_acc' => '2-1101',
                'nama_acc' => 'HUTANG DAGANG',
                'kelompok' => 2,
                'tipe' => 'DT',
                'kas' => 0,
                'bank' => 0,
                'posisi' => 'K',
            ],
            [    
                'induk_acc' => '2-1100',
                'kode_acc' => '2-1102',
                'nama_acc' => 'HUTANG PIHAK KETIGA EVELYN',
                'kelompok' => 2,
                'tipe' => 'DT',
                'kas' => 0,
                'bank' => 0,
                'posisi' => 'K',
            ],
            [    
                'induk_acc' => '2-1100',
                'kode_acc' => '2-1130',
                'nama_acc' => 'HUTANG KARTU KREDIT',
                'kelompok' => 2,
                'tipe' => 'DT',
                'kas' => 0,
                'bank' => 0,
                'posisi' => 'K',
            ],
            [    
                'induk_acc' => '2-1100',
                'kode_acc' => '2-1140',
                'nama_acc' => 'HUTANG KONSINYASI',
                'kelompok' => 2,
                'tipe' => 'DT',
                'kas' => 0,
                'bank' => 0,
                'posisi' => 'K',
            ],
            [    
                'induk_acc' => '2-0000',
                'kode_acc' => '2-2000',
                'nama_acc' => 'HUTANG NON OPERASIONAL',
                'kelompok' => 2,
                'tipe' => 'HD',
                'kas' => 0,
                'bank' => 0,
                'posisi' => 'K',
            ],
            [    
                'induk_acc' => '2-0000',
                'kode_acc' => '2-3000',
                'nama_acc' => 'PENDAPATAN DITERIMA DIMUAKA',
                'kelompok' => 2,
                'tipe' => 'HD',
                'kas' => 0,
                'bank' => 0,
                'posisi' => 'K',
            ],
            [    
                'induk_acc' => '2-3000',
                'kode_acc' => '2-3100',
                'nama_acc' => 'UANG MUKA PESANAN PENJUALAN',
                'kelompok' => 2,
                'tipe' => 'DT',
                'kas' => 0,
                'bank' => 0,
                'posisi' => 'K',
            ],
            [    
                'induk_acc' => '2-0000',
                'kode_acc' => '2-4000',
                'nama_acc' => 'HUTANG PAJAK',
                'kelompok' => 2,
                'tipe' => 'HD',
                'kas' => 0,
                'bank' => 0,
                'posisi' => 'K',
            ],
            [    
                'induk_acc' => '2-4000',
                'kode_acc' => '2-4110',
                'nama_acc' => 'PPN KELUARAN',
                'kelompok' => 2,
                'tipe' => 'DT',
                'kas' => 0,
                'bank' => 0,
                'posisi' => 'K',
            ],
            [    
                'induk_acc' => '2-4000',
                'kode_acc' => '2-4120',
                'nama_acc' => 'HUTANG PAJAK',
                'kelompok' => 2,
                'tipe' => 'DT',
                'kas' => 0,
                'bank' => 0,
                'posisi' => 'K',
            ],
            [    
                'induk_acc' => '2-1000',
                'kode_acc' => '2-5000',
                'nama_acc' => 'JAMINAN KARYAWAN',
                'kelompok' => 2,
                'tipe' => 'DT',
                'kas' => 0,
                'bank' => 0,
                'posisi' => 'K',
            ],
            [    
                'induk_acc' => 'NULL',
                'kode_acc' => '3-0000',
                'nama_acc' => 'MODAL',
                'kelompok' => 3,
                'tipe' => 'HD',
                'kas' => 0,
                'bank' => 0,
                'posisi' => 'K',
            ],
            [    
                'induk_acc' => '3-0000',
                'kode_acc' => '3-1000',
                'nama_acc' => 'MODAL',
                'kelompok' => 3,
                'tipe' => 'DT',
                'kas' => 0,
                'bank' => 0,
                'posisi' => 'K',
            ],
            [    
                'induk_acc' => '3-0000',
                'kode_acc' => '3-2000',
                'nama_acc' => 'LABA DITAHAN',
                'kelompok' => 3,
                'tipe' => 'DT',
                'kas' => 0,
                'bank' => 0,
                'posisi' => 'K',
            ],
            [    
                'induk_acc' => '3-0000',
                'kode_acc' => '3-3000',
                'nama_acc' => 'LABA TAHUN BERJALAN',
                'kelompok' => 3,
                'tipe' => 'DT',
                'kas' => 0,
                'bank' => 0,
                'posisi' => 'K',
            ],
            [    
                'induk_acc' => '3-0000',
                'kode_acc' => '3-8000',
                'nama_acc' => 'PRIVE',
                'kelompok' => 3,
                'tipe' => 'DT',
                'kas' => 0,
                'bank' => 0,
                'posisi' => 'D',
            ],
            [    
                'induk_acc' => 'NULL',
                'kode_acc' => '4-0000',
                'nama_acc' => 'PENDAPATAN',
                'kelompok' => 4,
                'tipe' => 'HD',
                'kas' => 0,
                'bank' => 0,
                'posisi' => 'K',
            ],
            [    
                'induk_acc' => '4-0000',
                'kode_acc' => '4-1000',
                'nama_acc' => 'PENDAPATAN DAGANG',
                'kelompok' => 4,
                'tipe' => 'HD',
                'kas' => 0,
                'bank' => 0,
                'posisi' => 'K',
            ],
            [    
                'induk_acc' => '4-1000',
                'kode_acc' => '4-1100',
                'nama_acc' => 'PENDAPATAN JUAL',
                'kelompok' => 4,
                'tipe' => 'DT',
                'kas' => 0,
                'bank' => 0,
                'posisi' => 'K',
            ],
            [    
                'induk_acc' => 'NULL',
                'kode_acc' => '5-0000',
                'nama_acc' => 'HPP',
                'kelompok' => 5,
                'tipe' => 'HD',
                'kas' => 0,
                'bank' => 0,
                'posisi' => 'D',
            ],
            [    
                'induk_acc' => '5-0000',
                'kode_acc' => '5-1000',
                'nama_acc' => 'HPP PENJUALAN',
                'kelompok' => 5,
                'tipe' => 'HD',
                'kas' => 0,
                'bank' => 0,
                'posisi' => 'D',
            ],
            [    
                'induk_acc' => '5-1000',
                'kode_acc' => '5-1100',
                'nama_acc' => 'HPP PERSEDIAAN',
                'kelompok' => 5,
                'tipe' => 'DT',
                'kas' => 0,
                'bank' => 0,
                'posisi' => 'D',
            ],
            [    
                'induk_acc' => '5-1000',
                'kode_acc' => '5-1200',
                'nama_acc' => 'POTONGAN HUTANG',
                'kelompok' => 5,
                'tipe' => 'DT',
                'kas' => 0,
                'bank' => 0,
                'posisi' => 'D',
            ],
            [    
                'induk_acc' => '5-1000',
                'kode_acc' => '5-1300',
                'nama_acc' => 'BEBAN ANGKUT',
                'kelompok' => 5,
                'tipe' => 'DT',
                'kas' => 0,
                'bank' => 0,
                'posisi' => 'D',
            ],
            [    
                'induk_acc' => '5-0000',
                'kode_acc' => '5-2000',
                'nama_acc' => 'BIAYA LAIN',
                'kelompok' => 5,
                'tipe' => 'HD',
                'kas' => 0,
                'bank' => 0,
                'posisi' => 'D',
            ],
            [    
                'induk_acc' => '5-2000',
                'kode_acc' => '5-2100',
                'nama_acc' => 'RUSAK',
                'kelompok' => 5,
                'tipe' => 'DT',
                'kas' => 0,
                'bank' => 0,
                'posisi' => 'D',
            ],
            [    
                'induk_acc' => '5-2000',
                'kode_acc' => '5-2200',
                'nama_acc' => 'PENGATURAN STOK',
                'kelompok' => 5,
                'tipe' => 'DT',
                'kas' => 0,
                'bank' => 0,
                'posisi' => 'D',
            ],
            [    
                'induk_acc' => '5-2000',
                'kode_acc' => '5-2201',
                'nama_acc' => 'BONUS',
                'kelompok' => 5,
                'tipe' => 'DT',
                'kas' => 0,
                'bank' => 0,
                'posisi' => 'D',
            ],
            [    
                'induk_acc' => '5-2000',
                'kode_acc' => '5-2202',
                'nama_acc' => 'TUKAR POIN',
                'kelompok' => 5,
                'tipe' => 'DT',
                'kas' => 0,
                'bank' => 0,
                'posisi' => 'D',
            ],
            [    
                'induk_acc' => '5-2000',
                'kode_acc' => '5-2203',
                'nama_acc' => 'PEMAKAIAN PRIBADI',
                'kelompok' => 5,
                'tipe' => 'DT',
                'kas' => 0,
                'bank' => 0,
                'posisi' => 'D',
            ],
            [    
                'induk_acc' => 'NULL',
                'kode_acc' => '6-0000',
                'nama_acc' => 'BIAYA',
                'kelompok' => 6,
                'tipe' => 'HD',
                'kas' => 0,
                'bank' => 0,
                'posisi' => 'D',
            ],
            [    
                'induk_acc' => '6-0000',
                'kode_acc' => '6-1000',
                'nama_acc' => 'BIAYA UMUM',
                'kelompok' => 6,
                'tipe' => 'HD',
                'kas' => 0,
                'bank' => 0,
                'posisi' => 'D',
            ],
            [    
                'induk_acc' => '6-1000',
                'kode_acc' => '6-1100',
                'nama_acc' => 'BIAYA LISTRIK/AIR/TELEPON',
                'kelompok' => 6,
                'tipe' => 'DT',
                'kas' => 0,
                'bank' => 0,
                'posisi' => 'D',
            ],
            [    
                'induk_acc' => '6-1000',
                'kode_acc' => '6-1101',
                'nama_acc' => 'BIAYA SEWA',
                'kelompok' => 6,
                'tipe' => 'DT',
                'kas' => 0,
                'bank' => 0,
                'posisi' => 'D',
            ],
            [    
                'induk_acc' => '6-1000',
                'kode_acc' => '6-1102',
                'nama_acc' => 'BIAYA ATK',
                'kelompok' => 6,
                'tipe' => 'DT',
                'kas' => 0,
                'bank' => 0,
                'posisi' => 'D',
            ],
            [    
                'induk_acc' => '6-1000',
                'kode_acc' => '6-1103',
                'nama_acc' => 'BIAYA BUNGA PINJAMAN',
                'kelompok' => 6,
                'tipe' => 'DT',
                'kas' => 0,
                'bank' => 0,
                'posisi' => 'D',
            ],
            [    
                'induk_acc' => '6-1000',
                'kode_acc' => '6-1104',
                'nama_acc' => 'BIAYA INTERNET',
                'kelompok' => 6,
                'tipe' => 'DT',
                'kas' => 0,
                'bank' => 0,
                'posisi' => 'D',
            ],
            [    
                'induk_acc' => '6-1000',
                'kode_acc' => '6-1105',
                'nama_acc' => 'BIAYA PENGIRIMAN',
                'kelompok' => 6,
                'tipe' => 'DT',
                'kas' => 0,
                'bank' => 0,
                'posisi' => 'D',
            ],
            [    
                'induk_acc' => '6-1000',
                'kode_acc' => '6-1106',
                'nama_acc' => 'BIAYA ADMINISTRASI BANK',
                'kelompok' => 6,
                'tipe' => 'DT',
                'kas' => 0,
                'bank' => 0,
                'posisi' => 'D',
            ],
            [    
                'induk_acc' => '6-1000',
                'kode_acc' => '6-1107',
                'nama_acc' => 'BIAYA BBM KENDARAAN',
                'kelompok' => 6,
                'tipe' => 'DT',
                'kas' => 0,
                'bank' => 0,
                'posisi' => 'D',
            ],
            [    
                'induk_acc' => '6-1000',
                'kode_acc' => '6-1108',
                'nama_acc' => 'BIAYA PERAWATAN KENDARAAN',
                'kelompok' => 6,
                'tipe' => 'DT',
                'kas' => 0,
                'bank' => 0,
                'posisi' => 'D',
            ],
            [    
                'induk_acc' => '6-1000',
                'kode_acc' => '6-1109',
                'nama_acc' => 'BIAYA OBAT KARYAWAN',
                'kelompok' => 6,
                'tipe' => 'DT',
                'kas' => 0,
                'bank' => 0,
                'posisi' => 'D',
            ],
            [    
                'induk_acc' => '6-1000',
                'kode_acc' => '6-1110',
                'nama_acc' => 'BIAYA IURAN DAN ANGSURAN',
                'kelompok' => 6,
                'tipe' => 'DT',
                'kas' => 0,
                'bank' => 0,
                'posisi' => 'D',
            ],
            [    
                'induk_acc' => '6-1000',
                'kode_acc' => '6-1111',
                'nama_acc' => 'BIAYA KONSUMSI KARYAWAN',
                'kelompok' => 6,
                'tipe' => 'DT',
                'kas' => 0,
                'bank' => 0,
                'posisi' => 'D',
            ],
            [    
                'induk_acc' => '6-1000',
                'kode_acc' => '6-1112',
                'nama_acc' => 'BIAYA TOLL, PARKIR & RETRIBUSI',
                'kelompok' => 6,
                'tipe' => 'DT',
                'kas' => 0,
                'bank' => 0,
                'posisi' => 'D',
            ],
            [    
                'induk_acc' => '6-1000',
                'kode_acc' => '6-1113',
                'nama_acc' => 'BIAYA LAIN-LAIN PERJALANAN',
                'kelompok' => 6,
                'tipe' => 'DT',
                'kas' => 0,
                'bank' => 0,
                'posisi' => 'D',
            ],
            [    
                'induk_acc' => '6-1000',
                'kode_acc' => '6-1114',
                'nama_acc' => 'BIAYA PERLENGKAPAN KANTOR',
                'kelompok' => 6,
                'tipe' => 'DT',
                'kas' => 0,
                'bank' => 0,
                'posisi' => 'D',
            ],
            [    
                'induk_acc' => '6-1000',
                'kode_acc' => '6-1115',
                'nama_acc' => 'BIAYA PERJALANAN DINAS',
                'kelompok' => 6,
                'tipe' => 'DT',
                'kas' => 0,
                'bank' => 0,
                'posisi' => 'D',
            ],
            [    
                'induk_acc' => '6-1000',
                'kode_acc' => '6-1116',
                'nama_acc' => 'BIAYA PERAWATAN PERLENGKAPAN KANTOR',
                'kelompok' => 6,
                'tipe' => 'DT',
                'kas' => 0,
                'bank' => 0,
                'posisi' => 'D',
            ],
            [    
                'induk_acc' => '6-1000',
                'kode_acc' => '6-1117',
                'nama_acc' => 'BIAYA PAJAK KENDARAAN',
                'kelompok' => 6,
                'tipe' => 'DT',
                'kas' => 0,
                'bank' => 0,
                'posisi' => 'D',
            ],
            [    
                'induk_acc' => '6-1000',
                'kode_acc' => '6-1118',
                'nama_acc' => 'BIAYA KONSULTAN',
                'kelompok' => 6,
                'tipe' => 'DT',
                'kas' => 0,
                'bank' => 0,
                'posisi' => 'D',
            ],
            [    
                'induk_acc' => '6-1000',
                'kode_acc' => '6-1119',
                'nama_acc' => 'BIAYA PAJAK',
                'kelompok' => 6,
                'tipe' => 'DT',
                'kas' => 0,
                'bank' => 0,
                'posisi' => 'D',
            ],
            [    
                'induk_acc' => '6-1000',
                'kode_acc' => '6-1120',
                'nama_acc' => 'BIAYA TAK TERDUGA',
                'kelompok' => 6,
                'tipe' => 'DT',
                'kas' => 0,
                'bank' => 0,
                'posisi' => 'D',
            ],
            [    
                'induk_acc' => '6-1000',
                'kode_acc' => '6-1121',
                'nama_acc' => 'BIAYA DANA SOSIAL',
                'kelompok' => 6,
                'tipe' => 'DT',
                'kas' => 0,
                'bank' => 0,
                'posisi' => 'D',
            ],
            [    
                'induk_acc' => '6-1000',
                'kode_acc' => '6-1122',
                'nama_acc' => 'BIAYA ENTERTAIN',
                'kelompok' => 6,
                'tipe' => 'DT',
                'kas' => 0,
                'bank' => 0,
                'posisi' => 'D',
            ],
            [    
                'induk_acc' => '6-1000',
                'kode_acc' => '6-1123',
                'nama_acc' => 'BIAYA PEMELIHARAAN BANGUNAN',
                'kelompok' => 6,
                'tipe' => 'DT',
                'kas' => 0,
                'bank' => 0,
                'posisi' => 'D',
            ],
            [    
                'induk_acc' => '6-1000',
                'kode_acc' => '6-1124',
                'nama_acc' => 'BIAYA LEGAL ATAU PERIJINAN',
                'kelompok' => 6,
                'tipe' => 'DT',
                'kas' => 0,
                'bank' => 0,
                'posisi' => 'D',
            ],
            [    
                'induk_acc' => '6-1000',
                'kode_acc' => '6-1125',
                'nama_acc' => 'BIAYA ASURANSI',
                'kelompok' => 6,
                'tipe' => 'DT',
                'kas' => 0,
                'bank' => 0,
                'posisi' => 'D',
            ],
            [    
                'induk_acc' => '6-1000',
                'kode_acc' => '6-1126',
                'nama_acc' => 'BIAYA INSENTIF PERJUALAN',
                'kelompok' => 6,
                'tipe' => 'DT',
                'kas' => 0,
                'bank' => 0,
                'posisi' => 'D',
            ],
            [    
                'induk_acc' => '6-0000',
                'kode_acc' => '6-2000',
                'nama_acc' => 'BIAYA PEMASARAN',
                'kelompok' => 6,
                'tipe' => 'HD',
                'kas' => 0,
                'bank' => 0,
                'posisi' => 'D',
            ],
            [    
                'induk_acc' => '6-2000',
                'kode_acc' => '6-2001',
                'nama_acc' => 'BIAYA IKLAN',
                'kelompok' => 6,
                'tipe' => 'DT',
                'kas' => 0,
                'bank' => 0,
                'posisi' => 'D',
            ],
            [    
                'induk_acc' => '6-2000',
                'kode_acc' => '6-2002',
                'nama_acc' => 'BIAYA PROMOSI',
                'kelompok' => 6,
                'tipe' => 'DT',
                'kas' => 0,
                'bank' => 0,
                'posisi' => 'D',
            ],
            [    
                'induk_acc' => '6-0000',
                'kode_acc' => '6-3000',
                'nama_acc' => 'BIAYA GAJI DAN UPAH',
                'kelompok' => 6,
                'tipe' => 'HD',
                'kas' => 0,
                'bank' => 0,
                'posisi' => 'D',
            ],
            [    
                'induk_acc' => '6-3000',
                'kode_acc' => '6-3001',
                'nama_acc' => 'BIAYA GAJI PEGAWAI',
                'kelompok' => 6,
                'tipe' => 'DT',
                'kas' => 0,
                'bank' => 0,
                'posisi' => 'D',
            ],
            [    
                'induk_acc' => '6-3000',
                'kode_acc' => '6-3002',
                'nama_acc' => 'BIAYA UPAH KERJA',
                'kelompok' => 6,
                'tipe' => 'DT',
                'kas' => 0,
                'bank' => 0,
                'posisi' => 'D',
            ],
            [    
                'induk_acc' => '6-3000',
                'kode_acc' => '6-3003',
                'nama_acc' => 'BIAYA TUNJANGAN',
                'kelompok' => 6,
                'tipe' => 'DT',
                'kas' => 0,
                'bank' => 0,
                'posisi' => 'D',
            ],
            [    
                'induk_acc' => '6-0000',
                'kode_acc' => '6-4000',
                'nama_acc' => 'BIAYA OPERASIONAL',
                'kelompok' => 6,
                'tipe' => 'HD',
                'kas' => 0,
                'bank' => 0,
                'posisi' => 'D',
            ],
            [    
                'induk_acc' => '6-4000',
                'kode_acc' => '6-4001',
                'nama_acc' => 'BIAYA BELI BAHAN BAKU',
                'kelompok' => 6,
                'tipe' => 'DT',
                'kas' => 0,
                'bank' => 0,
                'posisi' => 'D',
            ],
            [    
                'induk_acc' => '6-4000',
                'kode_acc' => '6-4002',
                'nama_acc' => 'BIAYA OPERASIONAL TOKO',
                'kelompok' => 6,
                'tipe' => 'DT',
                'kas' => 0,
                'bank' => 0,
                'posisi' => 'D',
            ],
            [    
                'induk_acc' => '6-0000',
                'kode_acc' => '6-5000',
                'nama_acc' => 'BIAYA PENYUSUTAN',
                'kelompok' => 6,
                'tipe' => 'HD',
                'kas' => 0,
                'bank' => 0,
                'posisi' => 'D',
            ],
            [    
                'induk_acc' => '6-5000',
                'kode_acc' => '6-5001',
                'nama_acc' => 'BIAYA PENYUSUTAN',
                'kelompok' => 6,
                'tipe' => 'DT',
                'kas' => 0,
                'bank' => 0,
                'posisi' => 'D',
            ],
            [    
                'induk_acc' => 'NULL',
                'kode_acc' => '6-6000',
                'nama_acc' => 'BEBAN LAIN-LAIN',
                'kelompok' => 6,
                'tipe' => 'HD',
                'kas' => 0,
                'bank' => 0,
                'posisi' => 'D',
            ],
            [    
                'induk_acc' => '6-6000',
                'kode_acc' => '6-6001',
                'nama_acc' => 'BEBAN POTONGAN PIUTANG USAHA',
                'kelompok' => 6,
                'tipe' => 'DT',
                'kas' => 0,
                'bank' => 0,
                'posisi' => 'D',
            ],
            [    
                'induk_acc' => '6-6000',
                'kode_acc' => '6-6002',
                'nama_acc' => 'BEBAN POTONGAN PENJUALAN',
                'kelompok' => 6,
                'tipe' => 'DT',
                'kas' => 0,
                'bank' => 0,
                'posisi' => 'D',
            ],
            [    
                'induk_acc' => 'NULL',
                'kode_acc' => '6-9000',
                'nama_acc' => 'BIAYA NON INVENTORY',
                'kelompok' => 6,
                'tipe' => 'HD',
                'kas' => 0,
                'bank' => 0,
                'posisi' => 'D',
            ],
            [    
                'induk_acc' => '6-9000',
                'kode_acc' => '6-9001',
                'nama_acc' => 'BIAYA BELANJA NON INVENTORY',
                'kelompok' => 6,
                'tipe' => 'DT',
                'kas' => 0,
                'bank' => 0,
                'posisi' => 'D',
            ],
            [    
                'induk_acc' => 'NULL',
                'kode_acc' => '7-0000',
                'nama_acc' => 'PENDAPATAN LAIN-LAIN',
                'kelompok' => 7,
                'tipe' => 'HD',
                'kas' => 0,
                'bank' => 0,
                'posisi' => 'K',
            ],
            [    
                'induk_acc' => '7-0000',
                'kode_acc' => '7-1100',
                'nama_acc' => 'PENDAPATAN POTONGAN HUTANG USAHA',
                'kelompok' => 7,
                'tipe' => 'DT',
                'kas' => 0,
                'bank' => 0,
                'posisi' => 'K',
            ],
            [    
                'induk_acc' => '7-0000',
                'kode_acc' => '7-1200',
                'nama_acc' => 'PENDAPATAN INSENTIF PEMBELIAN',
                'kelompok' => 7,
                'tipe' => 'DT',
                'kas' => 0,
                'bank' => 0,
                'posisi' => 'K',
            ]
        ]);
    }
}
